version: "3.3"
services:
  database:
    image: "mysql:5.7"
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    env_file:
      - .env
    depends_on:
      - database
    image: "wordpress:latest"
    ports:
      - '5000:80'
    environment:
      WORDPRESS_DB_HOST: 'database:3306'
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./wordpress:/var/www/html"

volumes:
  data: